FROM python:3.9-slim-buster

WORKDIR /app
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2 && pip install sqlalchemy

COPY your_job_offer ./your_job_offer

CMD ["python", "your_job_offer/jobs_db.py"]

