services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobs
    ports:
      - "5431:5432"
  db-tokens:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tokens
    ports:
      - "5430:5432"

  base:
    build:
      context: .
      dockerfile: deploy/Dockerfile.base
    image: base

  create-jobs-db:
    build:
      context: .
      dockerfile: deploy/Dockerfile.jobs_db
    volumes:
      - ./app_logs/:/app/app_logs
    restart: on-failure
    depends_on:
      - base
      - db
    env_file:
      - secrets/.env
  create-tokens-db:
    build:
      context: .
      dockerfile: deploy/Dockerfile.token_db
    volumes:
      - ./app_logs/:/app/app_logs
    restart: on-failure
    depends_on:
      - base
      - db-tokens 
    env_file:
      - secrets/.env

  parse-jobs-db:
    build:
      context: .
      dockerfile: deploy/Dockerfile.jobs_db_parsing
    volumes:
      - ./app_logs/:/app/app_logs
    restart: on-failure
    depends_on:
      - create-jobs-db
    env_file:
      - secrets/.env

  parse-vacancy-status:
    build:
      context: .
      dockerfile: deploy/Dockerfile.vacancy_status_parsing
    volumes:
      - ./app_logs/:/app/app_logs
    restart: on-failure
    depends_on:
      - create-jobs-db
    env_file:
      - secrets/.env

  app:
    build:
      context: .
      dockerfile: deploy/Dockerfile.app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - parse-jobs-db
      - parse-vacancy-status
      - create-tokens-db
    env_file:
      - secrets/.env
