FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get -y install libpq-dev gcc
COPY pyproject.toml build/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY your_job_offer ./your_job_offer
RUN pip install --no-cache-dir -e .

RUN apt-get -y install cron
COPY crontab.jobs_db /etc/cron.d/cron_schedule
RUN chmod 0644 /etc/cron.d/cron_schedule
RUN crontab /etc/cron.d/cron_schedule
#CMD ["/usr/local/bin/python", "/app/your_job_offer/repository/vacancies_repository/parsing.py" ]
CMD ["cron", "-f"]
