FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get -y install libpq-dev gcc
COPY pyproject.toml build/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY your_job_offer ./your_job_offer
RUN pip install --no-cache-dir -e .

CMD ["python", "your_job_offer/jobs_db.py"]

