FROM python:3.9-slim-buster
WORKDIR /app
RUN apt-get update && apt-get -y install libpq-dev build-essential libpoppler-cpp-dev pkg-config python3-dev
COPY secrets/ ./secrets
RUN mkdir -p app_logs
COPY pyproject.toml build/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY your_job_offer/ ./your_job_offer
RUN pip install --no-cache-dir -e .

RUN apt-get -y install cron
COPY crontab.jobs_db /etc/cron.d/cron_schedule
RUN chmod 0644 /etc/cron.d/cron_schedule
RUN crontab /etc/cron.d/cron_schedule
CMD ["cron", "-f"]
