services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobs
    ports:
      - "5431:5432"
  db-tokens:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tokens
    ports:
      - "5430:5432"

  create-jobs-db:
    build:
      context: .
      dockerfile: Dockerfile.jobs_db
    volumes:
      - ./:/app
    restart: on-failure
    depends_on:
      - db
  create-tokens-db:
    build:
      context: .
      dockerfile: Dockerfile.token_db
    volumes:
      - ./:/app
    restart: on-failure
    depends_on:
      - db-tokens


  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "0.0.0.0:8080:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - create-jobs-db
      - create-tokens-db

